### ISSUE TITLE
Cpp review ✅

### ISSUE THREAD

**Issue by Tbelleng** [eytanlvy/cpp_course#1]
Bon Cpp Eytan, les classes sont implémentées comme demandé, les tests CI et de sécurité sont passés avec succès, je te souhaite bonne continuation 🛰️

**Comment by uhit64** [comment]
Eytan est un élève sérieux et modèle ceux malgré quelques folies hasardeuse et son besoin régulirer de se proméner à Gallieni, j'ouvre bientôt les CI pour évaluer le bon fonctionnement du travail.

**Comment by Tbelleng** [comment]
Merci Doctorant El-Kamel pour votre aide cette année a nos éleves les plus en difficultés, je ferme l'issue des confirmation de vos tests afin de valider le travail d'Eytan 🤝

**Comment by Tbelleng** [comment]
TP4 toujours pas fini ? 😓
